# Generated by Django 4.1 on 2023-12-02 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_rename_games_review_alter_review_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='note',
            new_name='rating',
        ),
    ]
