# Generated by Django 4.1 on 2023-11-30 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('description', models.TextField(max_length=100, verbose_name='Descricao')),
                ('review', models.CharField(max_length=500, verbose_name='Review')),
                ('note', models.IntegerField(verbose_name='Nota')),
                ('release_date', models.DateField(verbose_name='Data de Lançamento')),
            ],
            options={
                'verbose_name': 'Games',
                'verbose_name_plural': 'Games',
                'ordering': ['id'],
            },
        ),
    ]
