# Generated by Django 4.1 on 2023-12-06 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorites',
            old_name='name',
            new_name='review_name',
        ),
    ]
